/**
 * PiExtensionSource — the T3 Code runtime extension for Pi.
 *
 * Pi executes tool calls without asking by default. This extension hooks
 * `tool_call`, and for mutating tools (`bash`, `write`, `edit`) raises a
 * blocking dialog through Pi's extension UI protocol. In `--mode rpc` that
 * dialog surfaces as an `extension_ui_request` event on stdout, which the
 * Pi adapter maps onto T3's first-class approval flow (`request.opened` /
 * `request.resolved`); the structured request rides inside the dialog title
 * behind the `t3-approval:v1:` marker (see PiRpcModel.ts).
 *
 * It also fills the temporary gap between Anthropic adding refusal fallback
 * support for a model and Pi's catalog advertising that model's allowed
 * fallback targets. This stays in the original provider request, so a
 * fallback cannot replay tool calls that already completed.
 *
 * The source is embedded as a string and materialized under the server's
 * state directory at driver creation, then loaded via `pi -e <path>`. This
 * keeps the server deployable as a single artifact — no packaged resource
 * files to resolve at runtime.
 *
 * `T3_PI_APPROVAL_MODE=off` (set for full-access threads) disables gating.
 *
 * [fork:pi] This module is fork-local. See docs/internals/fork-pi-provider.md.
 *
 * @module provider/piRpc/PiExtensionSource
 */
import * as Effect from "effect/Effect";
import type * as FileSystem from "effect/FileSystem";
import type * as Path from "effect/Path";

export const T3_PI_APPROVAL_MODE_ENV = "T3_PI_APPROVAL_MODE";
export const T3_PI_EXTENSION_FILENAME = "t3-approvals.ts";

/**
 * Extension source, executed by Pi's own extension loader (TypeScript is
 * supported natively). Keep this dependency-free and defensive: it runs in
 * a different process against whatever Pi version the user has installed.
 */
export const T3_PI_EXTENSION_SOURCE = `\
// T3 Code runtime integration for Pi. Generated by T3 Code — do not edit;
// this file is rewritten whenever the embedded source changes.
const APPROVAL_TITLE_PREFIX = "t3-approval:v1:";
const GATED_TOOLS = new Set(["bash", "write", "edit"]);
const OPTIONS = ["Allow", "Always allow", "Deny"];
const MAX_DETAIL_CHARS = 400;
const ANTHROPIC_SERVER_SIDE_FALLBACK_BETA =
  "server-side-fallback-2026-07-01";
const ANTHROPIC_FALLBACK_MODELS = new Map([
  [
    "claude-fable-5-1",
    [
      {
        model: "claude-opus-5",
        cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
      },
      {
        model: "claude-opus-4-8",
        cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
      },
    ],
  ],
]);

function truncate(value, limit) {
  return typeof value === "string" && value.length > limit
    ? value.slice(0, limit) + "…"
    : value;
}

function summarize(toolName, input) {
  if (typeof input?.command === "string") return truncate(input.command, MAX_DETAIL_CHARS);
  for (const key of ["path", "file_path", "filePath", "file"]) {
    if (typeof input?.[key] === "string") return truncate(input[key], MAX_DETAIL_CHARS);
  }
  return undefined;
}

function compactArgs(toolName, input) {
  if (input === null || typeof input !== "object") return {};
  if (toolName === "bash") {
    return { command: truncate(input.command, 2000) };
  }
  const args = {};
  for (const key of ["path", "file_path", "filePath", "file"]) {
    if (typeof input[key] === "string") {
      args.path = input[key];
      break;
    }
  }
  if (typeof input.content === "string") args.contentLength = input.content.length;
  if (typeof input.oldText === "string") args.oldText = truncate(input.oldText, 500);
  if (typeof input.newText === "string") args.newText = truncate(input.newText, 500);
  return args;
}

function anthropicFallbacks(ctx) {
  if (ctx?.model?.provider !== "anthropic") return undefined;
  const nativeFallbacks = ctx.model.compat?.allowedFallbackModels;
  if (Array.isArray(nativeFallbacks) && nativeFallbacks.length > 0) return undefined;
  return ANTHROPIC_FALLBACK_MODELS.get(ctx.model.id);
}

function addAnthropicBeta(headers, beta) {
  if (headers === null || typeof headers !== "object") return;
  const existingKey = Object.keys(headers).find(
    (key) => key.toLowerCase() === "anthropic-beta",
  );
  const key = existingKey ?? "anthropic-beta";
  const features = typeof headers[key] === "string"
    ? headers[key].split(",").map((feature) => feature.trim()).filter(Boolean)
    : [];
  if (!features.includes(beta)) features.push(beta);
  headers[key] = features.join(",");
}

function priceAnthropicFallback(message, fallback) {
  const usage = message?.usage;
  if (usage === null || typeof usage !== "object") return undefined;
  const input = typeof usage.input === "number" ? usage.input : 0;
  const output = typeof usage.output === "number" ? usage.output : 0;
  const cacheRead = typeof usage.cacheRead === "number" ? usage.cacheRead : 0;
  const cacheWrite = typeof usage.cacheWrite === "number" ? usage.cacheWrite : 0;
  const longWrite = typeof usage.cacheWrite1h === "number" ? usage.cacheWrite1h : 0;
  const shortWrite = Math.max(0, cacheWrite - longWrite);
  const cost = {
    input: fallback.cost.input * input / 1_000_000,
    output: fallback.cost.output * output / 1_000_000,
    cacheRead: fallback.cost.cacheRead * cacheRead / 1_000_000,
    cacheWrite:
      (fallback.cost.cacheWrite * shortWrite + fallback.cost.input * 2 * longWrite) /
      1_000_000,
  };
  return {
    ...message,
    usage: {
      ...usage,
      cost: { ...cost, total: cost.input + cost.output + cost.cacheRead + cost.cacheWrite },
    },
  };
}

export default function t3Approvals(pi) {
  pi.on("before_provider_headers", (event, ctx) => {
    if (!anthropicFallbacks(ctx)) return;
    addAnthropicBeta(event?.headers, ANTHROPIC_SERVER_SIDE_FALLBACK_BETA);
  });

  pi.on("before_provider_request", (event, ctx) => {
    const fallbacks = anthropicFallbacks(ctx);
    const payload = event?.payload;
    if (!fallbacks || payload === null || typeof payload !== "object") return undefined;
    if (Array.isArray(payload.fallbacks) && payload.fallbacks.length > 0) return undefined;
    return {
      ...payload,
      fallbacks: fallbacks.map((fallback) => ({ model: fallback.model })),
    };
  });

  pi.on("message_end", (event, ctx) => {
    const message = event?.message;
    const fallbacks = anthropicFallbacks(ctx);
    if (message?.role !== "assistant" || !fallbacks) return undefined;
    const fallback = fallbacks.find((candidate) => candidate.model === message.model);
    if (!fallback) return undefined;
    const priced = priceAnthropicFallback(message, fallback);
    return priced ? { message: priced } : undefined;
  });

  const mode = (globalThis.process?.env?.T3_PI_APPROVAL_MODE ?? "gated").toLowerCase();
  if (mode === "off") return;
  const allowedForSession = new Set();

  pi.on("tool_call", async (event, ctx) => {
    const toolName = typeof event?.toolName === "string" ? event.toolName : "tool";
    if (!GATED_TOOLS.has(toolName)) return undefined;
    if (allowedForSession.has(toolName)) return undefined;

    const input = event?.input ?? {};
    const payload = {
      toolName,
      detail: summarize(toolName, input),
      args: compactArgs(toolName, input),
    };

    let choice;
    try {
      choice = await ctx.ui.select(APPROVAL_TITLE_PREFIX + JSON.stringify(payload), OPTIONS);
    } catch {
      choice = undefined;
    }

    if (choice === "Always allow") {
      allowedForSession.add(toolName);
      return undefined;
    }
    if (choice === "Allow") return undefined;
    return {
      block: true,
      reason:
        choice === "Deny"
          ? "The user denied this tool call in T3 Code."
          : "The tool call was cancelled in T3 Code.",
    };
  });
}
`;

/**
 * Write the extension into `dir` (creating it) when missing or stale.
 * Returns the absolute extension path to pass via `pi -e`.
 */
export const ensurePiExtensionFile = Effect.fn("ensurePiExtensionFile")(function* (input: {
  readonly fileSystem: FileSystem.FileSystem;
  readonly path: Path.Path;
  readonly dir: string;
}) {
  const { fileSystem, path } = input;
  const extensionPath = path.join(input.dir, T3_PI_EXTENSION_FILENAME);
  const existing = yield* fileSystem
    .readFileString(extensionPath)
    .pipe(Effect.orElseSucceed(() => undefined));
  if (existing === T3_PI_EXTENSION_SOURCE) {
    return extensionPath;
  }
  yield* fileSystem.makeDirectory(input.dir, { recursive: true }).pipe(Effect.ignore);
  yield* fileSystem.writeFileString(extensionPath, T3_PI_EXTENSION_SOURCE);
  return extensionPath;
});
