/**
 * PiExtensionSource — the T3 Code approval-gating extension for Pi.
 *
 * Pi executes tool calls without asking by default. This extension hooks
 * `tool_call`, and for mutating tools (`bash`, `write`, `edit`) raises a
 * blocking dialog through Pi's extension UI protocol. In `--mode rpc` that
 * dialog surfaces as an `extension_ui_request` event on stdout, which the
 * Pi adapter maps onto T3's first-class approval flow (`request.opened` /
 * `request.resolved`); the structured request rides inside the dialog title
 * behind the `t3-approval:v1:` marker (see PiRpcModel.ts).
 *
 * The source is embedded as a string and materialized under the server's
 * state directory at driver creation, then loaded via `pi -e <path>`. This
 * keeps the server deployable as a single artifact — no packaged resource
 * files to resolve at runtime.
 *
 * `T3_PI_APPROVAL_MODE=off` (set for full-access threads) disables gating.
 *
 * [fork:pi] This module is fork-local. See docs/internals/fork-pi-provider.md.
 *
 * @module provider/piRpc/PiExtensionSource
 */
import * as Effect from "effect/Effect";
import type * as FileSystem from "effect/FileSystem";
import type * as Path from "effect/Path";

export const T3_PI_APPROVAL_MODE_ENV = "T3_PI_APPROVAL_MODE";
export const T3_PI_EXTENSION_FILENAME = "t3-approvals.ts";

/**
 * Extension source, executed by Pi's own extension loader (TypeScript is
 * supported natively). Keep this dependency-free and defensive: it runs in
 * a different process against whatever Pi version the user has installed.
 */
export const T3_PI_EXTENSION_SOURCE = `\
// T3 Code approval gating for Pi. Generated by T3 Code — do not edit;
// this file is rewritten whenever the embedded source changes.
const APPROVAL_TITLE_PREFIX = "t3-approval:v1:";
const GATED_TOOLS = new Set(["bash", "write", "edit"]);
const OPTIONS = ["Allow", "Always allow", "Deny"];
const MAX_DETAIL_CHARS = 400;

function truncate(value, limit) {
  return typeof value === "string" && value.length > limit
    ? value.slice(0, limit) + "…"
    : value;
}

function summarize(toolName, input) {
  if (typeof input?.command === "string") return truncate(input.command, MAX_DETAIL_CHARS);
  for (const key of ["path", "file_path", "filePath", "file"]) {
    if (typeof input?.[key] === "string") return truncate(input[key], MAX_DETAIL_CHARS);
  }
  return undefined;
}

function compactArgs(toolName, input) {
  if (input === null || typeof input !== "object") return {};
  if (toolName === "bash") {
    return { command: truncate(input.command, 2000) };
  }
  const args = {};
  for (const key of ["path", "file_path", "filePath", "file"]) {
    if (typeof input[key] === "string") {
      args.path = input[key];
      break;
    }
  }
  if (typeof input.content === "string") args.contentLength = input.content.length;
  if (typeof input.oldText === "string") args.oldText = truncate(input.oldText, 500);
  if (typeof input.newText === "string") args.newText = truncate(input.newText, 500);
  return args;
}

export default function t3Approvals(pi) {
  const mode = (globalThis.process?.env?.T3_PI_APPROVAL_MODE ?? "gated").toLowerCase();
  if (mode === "off") return;
  const allowedForSession = new Set();

  pi.on("tool_call", async (event, ctx) => {
    const toolName = typeof event?.toolName === "string" ? event.toolName : "tool";
    if (!GATED_TOOLS.has(toolName)) return undefined;
    if (allowedForSession.has(toolName)) return undefined;

    const input = event?.input ?? {};
    const payload = {
      toolName,
      detail: summarize(toolName, input),
      args: compactArgs(toolName, input),
    };

    let choice;
    try {
      choice = await ctx.ui.select(APPROVAL_TITLE_PREFIX + JSON.stringify(payload), OPTIONS);
    } catch {
      choice = undefined;
    }

    if (choice === "Always allow") {
      allowedForSession.add(toolName);
      return undefined;
    }
    if (choice === "Allow") return undefined;
    return {
      block: true,
      reason:
        choice === "Deny"
          ? "The user denied this tool call in T3 Code."
          : "The tool call was cancelled in T3 Code.",
    };
  });
}
`;

/**
 * Write the extension into `dir` (creating it) when missing or stale.
 * Returns the absolute extension path to pass via `pi -e`.
 */
export const ensurePiExtensionFile = Effect.fn("ensurePiExtensionFile")(function* (input: {
  readonly fileSystem: FileSystem.FileSystem;
  readonly path: Path.Path;
  readonly dir: string;
}) {
  const { fileSystem, path } = input;
  const extensionPath = path.join(input.dir, T3_PI_EXTENSION_FILENAME);
  const existing = yield* fileSystem
    .readFileString(extensionPath)
    .pipe(Effect.orElseSucceed(() => undefined));
  if (existing === T3_PI_EXTENSION_SOURCE) {
    return extensionPath;
  }
  yield* fileSystem.makeDirectory(input.dir, { recursive: true }).pipe(Effect.ignore);
  yield* fileSystem.writeFileString(extensionPath, T3_PI_EXTENSION_SOURCE);
  return extensionPath;
});
